### ISSUE TITLE
Savoir si c'est prêt à utiliser en production

### ISSUE THREAD

**Issue by shellking4** [PythonBenin/fedapay-python#1]
Est-ce que cette librairie est utilisable en production ? Qui l'utilise déjà pour un projet sérieux ? Quelqu'un de FedaPay m'a répondu récemment qu'ils n'ont pas de librairie en Python. Je voudrais implémenter un paiement avec FedaPay dans mon webservice. C'est pourquoi je demande. I don't want to run into weird issues. Please answer me ASAP

**Comment by nioperas06** [comment]
Nope. Vous pouvez développer votre propre package. J'archive ce dépôt.
